---
name: CI
on: push

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: jimeh/release-please-manifest-action@main
        id: release
        with:
          app-id: ${{ secrets.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
      - name: Create/update MAJOR tag
        if: ${{ steps.release.outputs.release_created }}
        uses: richardsimko/update-tag@v1
        with:
          tag_name: v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create/update MAJOR.MINOR tag
        if: ${{ steps.release.outputs.release_created }}
        uses: richardsimko/update-tag@v1
        with:
          tag_name: v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
